const axios = require('axios');
const WhatsAppProvider = require('../interface');
const logger = require('../../utils/logger');
const config = require('../../config');

/**
 * Baileys HTTP Provider
 * Calls external Baileys web service API
 */
class BaileysHttpProvider extends WhatsAppProvider {
  constructor() {
    super();
    this.baileysServiceUrl = config.baileys.serviceUrl;
    this.serviceApiKey = config.baileys.serviceApiKey;
    // Timeout configuration for HTTP calls (in ms) - from config or defaults
    this.timeout = config.baileys.timeout || 10000;
    this.sendTimeout = config.baileys.sendTimeout || 15000;
    
    if (!this.baileysServiceUrl) {
      throw new Error('WhatsApp service URL not configured. Set BAILEYS_SERVICE_URL in .env');
    }
    
    if (!this.serviceApiKey) {
      logger.warn('⚠️  BAILEYS_SERVICE_API_KEY not configured - requests may fail if service requires authentication');
    }
  }

  /**
   * Get HTTP headers for Baileys service
   */
  _getHeaders() {
    const headers = {
      'Content-Type': 'application/json'
    };
    
    if (this.serviceApiKey) {
      headers['X-API-Token'] = this.serviceApiKey;
    }
    
    return headers;
  }

  /**
   * Get axios config with timeout
   * @param {boolean} isSendOperation - True for send operations (longer timeout)
   */
  _getAxiosConfig(isSendOperation = false) {
    return {
      headers: this._getHeaders(),
      timeout: isSendOperation ? this.sendTimeout : this.timeout
    };
  }

  /**
   * Initialize a new WhatsApp account/device
   */
  async initialize(initConfig) {
    const { accountId, accountIdentifier, workspaceId } = initConfig;
    
    try {
      logger.info(`Initializing Baileys device via HTTP: ${accountIdentifier}`);
      
      const response = await axios.post(
        `${this.baileysServiceUrl}/devices`,
        {
          userId: `workspace_${workspaceId}`,
          alias: `account_${accountId}`
          // sessionId is auto-generated by Baileys: user_{userId}_device_{alias}
        },
        this._getAxiosConfig()
      );

      const data = response.data;
      const externalDeviceId = data.device?.id;
      const baileysSessionId = data.device?.sessionId; // Baileys generates this
      const baileysApiKey = data.device?.apiKey; // Device API key from Baileys

      // Store external device ID, Baileys session ID, and device API key for later use
      if (externalDeviceId) {
        const WhatsAppAccount = require('../../models/WhatsAppAccount');

        // Update external device ID
        await WhatsAppAccount.updateExternalDeviceId(accountId, externalDeviceId);

        // Update account_identifier with Baileys' actual sessionId
        if (baileysSessionId && baileysSessionId !== accountIdentifier) {
          await WhatsAppAccount.updateAccountIdentifier(accountId, baileysSessionId);
          logger.info(`Updated account ${accountId} identifier to Baileys sessionId: ${baileysSessionId}`);
        }

        // Note: Device API key is managed by Baileys service, not stored in our database
        // API keys are validated directly with Baileys service when used
      }
      
      // Get QR code if included in initial response
      let qrCode = data.qr || data.qrCode || data.device?.qr;
      
      // Setup webhook immediately to receive QR when it's ready
      if (externalDeviceId) {
        try {
          const webhookUrl = `${require('../../config').app.url}/api/webhooks/provider`;
          
          await axios.put(
            `${this.baileysServiceUrl}/devices/${externalDeviceId}/settings/webhook`,
            {
              webhookEnabled: true,
              webhookUrl: webhookUrl,
              webhookEvents: ['message', 'connection', 'qr']
            },
            { headers: this._getHeaders() }
          );
          
          logger.info(`Webhook configured for device ${externalDeviceId} during initialization`);
        } catch (webhookError) {
          logger.warn('Could not setup webhook during initialization:', webhookError.message);
        }
      }
      
      // QR will arrive via webhook if not in initial response
      // Frontend should poll /api/whatsapp/devices/:id/qr endpoint
      
      return {
        accountId,
        accountIdentifier: baileysSessionId || accountIdentifier, // Use Baileys' sessionId
        externalDeviceId,
        qrCode: qrCode || null,
        status: data.device?.status === 'connected' ? 'connected' : 'connecting',
        phoneNumber: data.device?.phoneNumber || null
      };
    } catch (error) {
      logger.error('Baileys HTTP initialize error:', error.response?.data || error.message);
      throw new Error('Failed to initialize device: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Send text message
   */
  async sendText(accountIdentifier, recipient, text) {
    try {
      logger.info(`Sending message via Baileys: sessionId=${accountIdentifier}, recipient=${recipient}`);
      
      const response = await axios.post(
        `${this.baileysServiceUrl}/send`,
        {
          sessionId: accountIdentifier,
          recipient: recipient,
          message: text
        },
        { 
          headers: this._getHeaders(),
          timeout: this.sendTimeout
        }
      );

      return {
        messageId: response.data.messageId || response.data.data?.messageId,
        status: 'sent'
      };
    } catch (error) {
      const errorMessage = error.response?.data?.error || error.message;
      logger.error('Baileys HTTP sendText error:', { error: errorMessage, sessionId: accountIdentifier });
      
      // Check for connection-related errors
      if (errorMessage && (
        errorMessage.toLowerCase().includes('connection closed') ||
        errorMessage.toLowerCase().includes('disconnected') ||
        errorMessage.toLowerCase().includes('not connected')
      )) {
        throw new Error('WhatsApp account is disconnected. Please reconnect your account before sending messages.');
      }
      
      throw new Error('Failed to send message: ' + errorMessage);
    }
  }

  /**
   * Send media message
   */
  async sendMedia(accountIdentifier, recipient, media) {
    try {
      let endpoint = '';
      let payload = {
        sessionId: accountIdentifier,
        recipient: recipient
      };

      switch (media.type) {
        case 'image':
          endpoint = '/send/image';
          payload.fileId = media.fileId;
          payload.caption = media.caption || '';
          break;
        case 'document':
          endpoint = '/send/document';
          payload.fileId = media.fileId;
          payload.fileName = media.fileName || 'document';
          break;
        case 'video':
          endpoint = '/send/video';
          payload.fileId = media.fileId;
          payload.caption = media.caption || '';
          break;
        case 'audio':
          endpoint = '/send/audio';
          payload.fileId = media.fileId;
          break;
        default:
          throw new Error('Unsupported media type: ' + media.type);
      }

      const response = await axios.post(
        `${this.baileysServiceUrl}${endpoint}`,
        payload,
        { 
          headers: this._getHeaders(),
          timeout: this.sendTimeout
        }
      );

      return {
        messageId: response.data.messageId || response.data.data?.messageId,
        status: 'sent'
      };
    } catch (error) {
      logger.error('Baileys HTTP sendMedia error:', error.response?.data || error.message);
      throw new Error('Failed to send media: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get account status
   */
  async getStatus(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot get status: external_device_id not found for ${accountIdentifier}`);
        return { status: 'disconnected' };
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}`,
        this._getAxiosConfig()
      );

      // Handle different response formats from Baileys service
      // Format 1: { success: true, device: { status, phoneNumber } }
      // Format 2: { device: { status, phoneNumber } }
      // Format 3: { status, phoneNumber } (direct)
      const device = response.data.device || response.data.data?.device || response.data;
      
      // Map Baileys status to our allowed ENUM values
      // Allowed: 'connecting', 'connected', 'disconnected', 'failed'
      // Reference: API_CURL_COMMANDS.md - status values: "connected", "pending", "disconnected"
      const statusMap = {
        'connected': 'connected',
        'connecting': 'connecting',
        'pending': 'connecting', // Map pending to connecting
        'reconnecting': 'connecting', // Map reconnecting to connecting
        'disconnected': 'disconnected',
        'failed': 'failed',
        'error': 'failed',
        'offline': 'disconnected'
      };
      
      const baileysStatus = device.status || 'disconnected';
      const mappedStatus = statusMap[baileysStatus.toLowerCase()] || 'disconnected';
      
      return {
        status: mappedStatus,
        phoneNumber: device.phoneNumber || null
      };
    } catch (error) {
      logger.error('Baileys HTTP getStatus error:', error.response?.data || error.message);
      return { status: 'disconnected' };
    }
  }

  /**
   * Get QR code
   */
  async getQRCode(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot get QR: external_device_id not found for ${accountIdentifier}`);
        return null;
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/qr`,
        this._getAxiosConfig()
      );

      return response.data.qr || response.data.qrCode || response.data.data?.qrCode || null;
    } catch (error) {
      logger.error('Baileys HTTP getQRCode error:', error.response?.data || error.message);
      return null;
    }
  }

  /**
   * Disconnect account (logout)
   */
  async disconnect(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot disconnect: external_device_id not found for ${accountIdentifier}`);
        return;
      }

      await axios.post(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/logout`,
        {},
        { headers: this._getHeaders() }
      );
      
      logger.info(`Logged out device ${account.external_device_id} (${accountIdentifier})`);
    } catch (error) {
      logger.error('Baileys HTTP disconnect error:', error.response?.data || error.message);
      throw new Error('Failed to disconnect: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Login device (trigger QR code generation for reconnection)
   */
  async login(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot login: external_device_id not found for ${accountIdentifier}`);
        throw new Error('Device not found');
      }

      const response = await axios.post(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/login`,
        {},
        { headers: this._getHeaders() }
      );
      
      logger.info(`Login initiated for device ${account.external_device_id} (${accountIdentifier})`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP login error:', error.response?.data || error.message);
      throw new Error('Failed to login: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Delete device from Baileys service
   */
  async deleteDevice(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot delete: external_device_id not found for ${accountIdentifier}`);
        return;
      }

      // First logout, then delete
      try {
        await axios.post(
          `${this.baileysServiceUrl}/devices/${account.external_device_id}/logout`,
          {},
          { headers: this._getHeaders() }
        );
        logger.info(`Logged out device ${account.external_device_id} before deletion`);
      } catch (logoutError) {
        logger.warn(`Logout failed (device may already be disconnected):`, logoutError.message);
      }

      // Delete device from Baileys service
      await axios.delete(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}`,
        { headers: this._getHeaders() }
      );
      
      logger.info(`Deleted device ${account.external_device_id} from Baileys service (${accountIdentifier})`);
    } catch (error) {
      logger.error('Baileys HTTP deleteDevice error:', error.response?.data || error.message);
      throw new Error('Failed to delete device: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Setup event listeners (webhook registration)
   * Note: Webhook is now configured during initialize(), so this is a fallback
   */
  async setupEventListeners(accountIdentifier, onEvent) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        logger.warn(`Cannot setup webhook: external_device_id not found for ${accountIdentifier}`);
        return;
      }
      
      // Register webhook with Baileys service using external device ID
      // This is idempotent - safe to call multiple times
      const webhookUrl = `${config.app.url}/api/webhooks/provider`;
      
      await axios.put(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/webhook`,
        {
          webhookEnabled: true,
          webhookUrl: webhookUrl,
          webhookEvents: ['message', 'connection', 'qr']
        },
        { headers: this._getHeaders() }
      );

      logger.info(`Event listeners (webhook) setup for device ${account.external_device_id} (${accountIdentifier})`);
    } catch (error) {
      logger.error('Baileys HTTP setupEventListeners error:', error.response?.data || error.message);
      // Don't throw - webhook setup is optional
    }
  }

  /**
   * Get contacts from WhatsApp
   * Endpoint: GET /devices/{deviceId}/contacts
   */
  async getContacts(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/contacts`,
        { headers: this._getHeaders() }
      );

      return response.data.contacts || [];
    } catch (error) {
      logger.error('Baileys HTTP getContacts error:', error.response?.data || error.message);
      throw new Error('Failed to get contacts: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get chats from WhatsApp
   * Endpoint: GET /devices/{deviceId}/chats
   * Reference: API_CURL_COMMANDS.md section 3.2
   */
  async getChats(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/chats`,
        { headers: this._getHeaders() }
      );

      return response.data.chats || [];
    } catch (error) {
      logger.error('Baileys HTTP getChats error:', error.response?.data || error.message);
      throw new Error('Failed to get chats: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get groups from WhatsApp
   * Endpoint: GET /devices/{deviceId}/groups
   * Reference: API_CURL_COMMANDS.md section 3.3
   */
  async getGroups(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/groups`,
        { headers: this._getHeaders() }
      );

      return response.data.groups || [];
    } catch (error) {
      logger.error('Baileys HTTP getGroups error:', error.response?.data || error.message);
      throw new Error('Failed to get groups: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get messages from WhatsApp (Baileys service)
   * Endpoint: GET /messages?sessionId={sessionId}&limit={limit}&offset={offset}
   * Reference: API_CURL_COMMANDS.md section 2.7
   * 
   * Note: This method is available for fetching message history from Baileys if needed,
   * but the main /messages endpoint in WA-Gateway only returns messages sent/received
   * through THIS service (stored in database). This method can be used for admin/debugging purposes.
   */
  async getMessages(accountIdentifier, options = {}) {
    try {
      const { limit = 50, offset = 0 } = options;

      const response = await axios.get(
        `${this.baileysServiceUrl}/messages`,
        {
          params: {
            sessionId: accountIdentifier,
            limit,
            offset
          },
          headers: this._getHeaders()
        }
      );

      return response.data.messages || [];
    } catch (error) {
      logger.error('Baileys HTTP getMessages error:', error.response?.data || error.message);
      throw new Error('Failed to get messages: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get AI settings from Baileys service
   * Endpoint: GET /devices/{deviceId}/settings/ai
   */
  async getAISettings(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/ai`,
        { headers: this._getHeaders() }
      );

      logger.info(`AI settings fetched for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP getAISettings error:', error.response?.data || error.message);
      // Return empty object if settings don't exist yet
      if (error.response?.status === 404) {
        return {};
      }
      throw new Error('Failed to get AI settings: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Configure AI auto-reply settings
   */
  async configureAI(accountIdentifier, aiSettings) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.put(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/ai`,
        aiSettings,
        { headers: this._getHeaders() }
      );

      logger.info(`AI settings configured for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP configureAI error:', error.response?.data || error.message);
      throw new Error('Failed to configure AI: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Sync auto-reply rules to Baileys service
   * Baileys expects rules as a textarea-formatted string
   */
  async syncAutoReplyRules(accountIdentifier, rules) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      // Format rules as textarea string (JSON stringified for Baileys textarea)
      // Baileys service expects rules in textarea format, so we send as JSON string
      const baileysRules = rules.map(rule => ({
        id: rule.id,
        name: rule.name,
        triggerType: rule.trigger_type,
        triggerValue: rule.trigger_value,
        replyMessage: rule.reply_message,
        isActive: rule.is_active,
        priority: rule.priority,
        delaySeconds: rule.delay_seconds || 0
      }));

      // Send rules as textarea content (JSON stringified)
      // Baileys expects this in a textarea, so we send as a text string
      const rulesText = JSON.stringify(baileysRules, null, 2);

      const response = await axios.put(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/auto-reply`,
        { rulesText: rulesText }, // Send as text string for textarea (field name might be rulesText)
        { headers: this._getHeaders() }
      );

      logger.info(`Auto-reply rules synced for device ${account.external_device_id} (${rules.length} rules)`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP syncAutoReplyRules error:', error.response?.data || error.message);
      throw new Error('Failed to sync auto-reply rules: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get business templates from Baileys service
   * Endpoint: GET /api/business-templates/:businessType or /api/business-templates/:businessType/:language
   * Auth: X-API-Token (or Authorization: Bearer based on user's earlier specification)
   * Reference: API_CURL_COMMANDS.md section 8.3
   */
  async getBusinessTemplates(accountIdentifier, businessType = null, language = null) {
    try {
      if (!businessType) {
        throw new Error('Business type is required');
      }

      // Extract base URL from BAILEYS_SERVICE_URL
      // e.g., http://localhost:3000/api/whatsapp -> http://localhost:3000
      // or http://localhost:3000/api/whatsapp -> http://localhost:3000
      const baseUrl = this.baileysServiceUrl.replace(/\/api\/whatsapp.*$/, '');
      
      // Build URL: /api/business-templates/{businessType} or /api/business-templates/{businessType}/{language}
      let url = `${baseUrl}/api/business-templates/${businessType}`;
      if (language) {
        url += `/${language}`;
      }

      // Use X-API-Token header (as per API_CURL_COMMANDS.md reference, section 8.3)
      const headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      };
      
      if (this.serviceApiKey) {
        headers['X-API-Token'] = this.serviceApiKey;
      }

      const response = await axios.get(url, { headers });

      logger.info(`Business templates loaded for type: ${businessType}${language ? ` (${language})` : ''}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP getBusinessTemplates error:', error.response?.data || error.message);
      throw new Error('Failed to load business templates: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Update business configuration in Baileys service
   * Business config is saved through AI settings endpoint
   * Reference: API_CURL_COMMANDS.md - PUT /devices/{id}/settings/ai
   */
  async updateBusinessConfig(accountIdentifier, businessConfig) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);
      
      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      // Map business config fields to AI settings format
      // Business config is part of AI settings in Baileys service
      // Handle structured data (productKnowledge and salesScripts can be objects)
      const aiSettingsPayload = {
        businessType: businessConfig.business_type || businessConfig.businessType,
        productKnowledge: businessConfig.productKnowledge || businessConfig.product_knowledge || null,
        salesScripts: businessConfig.salesScripts || businessConfig.sales_scripts || null,
        upsellStrategies: businessConfig.upsell_strategies || businessConfig.upsellStrategies || '',
        objectionHandling: businessConfig.objection_handling || businessConfig.objectionHandling || '',
        templateLanguage: businessConfig.template_language || businessConfig.templateLanguage || 'en'
      };

      const response = await axios.put(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/ai`,
        aiSettingsPayload,
        { headers: this._getHeaders() }
      );

      logger.info(`Business config updated for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP updateBusinessConfig error:', error.response?.data || error.message);
      throw new Error('Failed to update business config: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Upload file to Baileys storage
   */
  async uploadFile(userId, fileBuffer, fileName, fileType) {
    try {
      const FormData = require('form-data');
      const formData = new FormData();
      
      formData.append('file', fileBuffer, fileName);
      formData.append('fileType', fileType);

      const response = await axios.post(
        `${this.baileysServiceUrl}/files/users/${userId}`,
        formData,
        { 
          headers: {
            ...this._getHeaders(),
            ...formData.getHeaders()
          }
        }
      );

      return {
        fileId: response.data.file?.id,
        fileName: response.data.file?.fileName,
        fileType: response.data.file?.fileType,
        fileSize: response.data.file?.fileSize,
        url: response.data.file?.url
      };
    } catch (error) {
      logger.error('Baileys HTTP uploadFile error:', error.response?.data || error.message);
      throw new Error('Failed to upload file: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get file info
   */
  async getFileInfo(fileId) {
    try {
      const response = await axios.get(
        `${this.baileysServiceUrl}/files/${fileId}`,
        { headers: this._getHeaders() }
      );

      return response.data.file || null;
    } catch (error) {
      logger.error('Baileys HTTP getFileInfo error:', error.response?.data || error.message);
      return null;
    }
  }

  /**
   * Delete file
   */
  async deleteFile(fileId) {
    try {
      await axios.delete(
        `${this.baileysServiceUrl}/files/${fileId}`,
        { headers: this._getHeaders() }
      );

      logger.info(`Deleted file ${fileId}`);
      return true;
    } catch (error) {
      logger.error('Baileys HTTP deleteFile error:', error.response?.data || error.message);
      return false;
    }
  }

  /**
   * Get webhook settings for device
   * Endpoint: GET /devices/{deviceId}/settings/webhook
   */
  async getWebhookSettings(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);

      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/webhook`,
        { headers: this._getHeaders() }
      );

      logger.info(`Webhook settings retrieved for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP getWebhookSettings error:', error.response?.data || error.message);
      throw new Error('Failed to get webhook settings: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Update webhook settings for device
   * Endpoint: PUT /devices/{deviceId}/settings/webhook
   */
  async updateWebhookSettings(accountIdentifier, settings) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);

      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      const response = await axios.put(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}/settings/webhook`,
        settings,
        { headers: this._getHeaders() }
      );

      logger.info(`Webhook settings updated for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP updateWebhookSettings error:', error.response?.data || error.message);
      throw new Error('Failed to update webhook settings: ' + (error.response?.data?.error || error.message));
    }
  }

  /**
   * Get device information
   * Endpoint: GET /users/{userId}/devices or GET /devices/{deviceId}
   */
  async getDeviceInfo(accountIdentifier) {
    try {
      // Get external device ID from database
      const WhatsAppAccount = require('../../models/WhatsAppAccount');
      const account = await WhatsAppAccount.findByIdentifier(accountIdentifier);

      if (!account || !account.external_device_id) {
        throw new Error('Device not found or not initialized');
      }

      // Try to get device info from Baileys
      const response = await axios.get(
        `${this.baileysServiceUrl}/devices/${account.external_device_id}`,
        { headers: this._getHeaders() }
      );

      logger.info(`Device info retrieved for device ${account.external_device_id}`);
      return response.data;
    } catch (error) {
      logger.error('Baileys HTTP getDeviceInfo error:', error.response?.data || error.message);
      throw new Error('Failed to get device info: ' + (error.response?.data?.error || error.message));
    }
  }
}

module.exports = BaileysHttpProvider;

